# ~/.xinitrc

# ----- Environment Variables -----
source "$HOME/.config/x/exports.sh"

# Additional x settings
xset s off -dpms
xset m 1/1
xset -b

# Merge in the Xresources
xrdb -merge "$HOME/.config/x/Xresources"

# Setup the urxvt daemon
urxvtd -q -f &

# Start i3
exec i3
