#!/usr/bin/env bash
# ~/.config/scripts/wal-set
# A modified version of Dylan Araps' script (https://github.com/dylanaraps/bin/blob/master/wal-set)

# Import the colors generated by wal
source "${HOME}/.cache/wal/colors.sh"


killall -9 dunst
dunst -lb "$color3" -nb "$color3" -cb "$color3" -lf "$color7" -bf "$color7" -cf "$color7" -fn "${DUNST_FONT:-Terminus 12}" -geometry "${DUNST_SIZE:-300x30-40+40}" &

# Restart and re-theme polybar
$HOME/.config/polybar/launch.sh
