#!/usr/bin/env bash
# ~/.config/scripts/wal-set.sh
# A modified version of Dylan Araps' script (https://github.com/dylanaraps/bin/blob/master/wal-set)

# Import the colors generated by wal
source "${HOME}/.cache/wal/colors.sh"

# Restart and re-theme the notification system
killall -9 dunst
dunst \
    -lb "$color0" \
    -nb "$color0" \
    -cb "$color0" \
    -lf "#ffffff" \
    -bf "#ffffff" \
    -cf "#ffffff" \
    -fn "${DUNST_FONT:-Terminus 12}" \
    -geometry "${DUNST_SIZE:-300x30-40+40}" &

# Restart and re-theme polybar
$HOME/.config/polybar/launch.sh

# Copy and instantiate Emacs theming
if [ -d $HOME/.emacs.d/themes ]; then
  mkdir -p $HOME/.emacs.d/themes
fi

cp -f $HOME/.cache/wal/colors-emacs.el $HOME/.emacs.d/themes/wal.el
