# ~/.bashrc

# Automatically start the window manager at login
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    exec startx > $HOME/.i3-last-run.log 2>&1
fi

# Customize prompt
export PS1="\u@\h [\W] "

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Stop stupid beep
xset -b

# History settings
shopt -s histappend # Append, not rewrite ~/.bash_history
shopt -s cmdhist # Squash multi-line commands to one in history
export HISTTIMEFORMAT='[%F %T] '
export HISTSIZE=50000
export HISTFILESIZE=50000
export PROMPT_COMMAND='history -a'
export HISTCONTROL=ignoredups # colon-separated list
export HISTIGNORE="history" # colon-separated list and supports globs

# Aliaseses
alias dnd='cd /home/justa/projects/totty/dnd'
alias notes='cd /home/justa/projects/mollycule/gitlab/notes/'
alias resume='cd /home/justa/.career/resume/resume-master/'
alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias netstat='ss -pantu | column -t'

# Work Aliaseses
alias mw='cd /home/justa/projects/ncsa/mwt2/'

# Kubectl autocomplete
source <(kubectl completion bash)
alias k='kubectl'
complete -F __start_kubectl k

# Set env variable for Qt themes
# in response to wanting a dark theme for VirtualBox
export QT_QPA_PLATFORMTHEME=qt5ct

# Autocorrect previous command
eval "$(thefuck --alias)"

function ssh {
    echo -e '\033]2;'"SSH : $1"'\007'
    TERM="xterm-256color" /usr/bin/ssh $@
}

